// auto-generated by keystone-css — do not edit
import {
  colorTemplate,
  customTemplate,
  fontFamilyTemplate,
  fontWeightTemplate,
  fontVariantTemplate,
  spaceTemplate,
  sizeTemplate,
  pxTemplate,
  remTemplate,
  resetTemplate,
  responsiveTemplate
} from "@keystone-css/core/templates";

import _def from "../config.js";
import { tokens } from "./_tokens.js";

export const { makeColor } = colorTemplate.util(tokens);
export const { makeCustom } = customTemplate.util(tokens);
export const { makeFontFamily } = fontFamilyTemplate.util(tokens);
export const { makeFontWeight } = fontWeightTemplate.util(tokens);
export const { makeFontVariant } = fontVariantTemplate.util(tokens);
export const { makeSpace } = spaceTemplate.util(tokens);
export const { makeSize } = sizeTemplate.util(tokens);
export const { makePx } = pxTemplate.util(tokens);
export const { makeRem } = remTemplate.util(tokens);
export const { makeReset } = resetTemplate.util(tokens);
export const { makeResponsive } = responsiveTemplate.util(tokens);
export const { makeBorder } = _def.templates[0].util(tokens);
